name: Build Check

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    building-project:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - run: yarn
            - run: yarn lint
            - run: yarn build

    building-emails:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - run: yarn
            - run: yarn export:email
